### ISSUE TITLE
Static blue flame over normal soulfire animation

### ISSUE THREAD

**Issue by anoomolu** [MoriyaShiine/on-soul-fire#10]
### Mod version

1.20.1

### A description of the issue

Heya, I didn't really know how to title this, sorry.

When burning with normal fire, there's just the animated fire layer when in 3rd person view. However when on soul fire with this mod, there seems to be a static blue flame over a normally animated soulfire layer. I don't have recording software on my laptop, but below are some screenshots that might make it a bit clearer.

![image](https://github.com/MoriyaShiine/on-soul-fire/assets/77850233/fd48ba37-2b44-4f8f-95fe-c14bca5331b8)
![image](https://github.com/MoriyaShiine/on-soul-fire/assets/77850233/b20a4204-18fb-42e5-a9ec-d3a0785ef1eb)

![image](https://github.com/MoriyaShiine/on-soul-fire/assets/77850233/e9852e41-19fb-4755-827d-5037825b3413)
![image](https://github.com/MoriyaShiine/on-soul-fire/assets/77850233/4bfaf7dc-f17b-437f-a921-d09254ac39c9)

**Comment by MoriyaShiine** [comment]
Sorry, didn't see this until now! Do you have any other mods installed?

**Comment by anoomolu** [comment]
Hiya, no worries. That was a modded pack yes - when I opened it up to check just now, I wasn't able to reproduce the issue. Guessing it was some other mod being buggy ^^
