### ISSUE TITLE
Soul Fire effect only goes away once fully submerged in lava.

### ISSUE THREAD

**Issue by CommandGenius** [MoriyaShiine/on-soul-fire#14]
### Mod version (NOT Minecraft version)

1.20.6-r3

### A description of the issue

Soul Fire effect only goes away once fully submerged in lava.
![soulfiregif](https://github.com/MoriyaShiine/on-soul-fire/assets/83155590/9f04efd2-adea-42f4-99f6-fbe78a47d256)

### Log or crash report

hi

**Comment by MoriyaShiine** [comment]
This is just due to how collision in Minecraft works
