### ISSUE TITLE
Issue with skin second layer on multiplayer

### ISSUE THREAD

**Issue by Francy-chan** [MoriyaShiine/on-soul-fire#2]
So, I don't know why or how, but in multiplayer, the skin's second layer isn't rendered.

Notes:
-Tested with no other mods except the fabric api
-The server doesn't have the mod installed

**Comment by MoriyaShiine** [comment]
concern

Does this happen in singleplayer?

**Comment by Francy-chan** [comment]
Nope

**Comment by MoriyaShiine** [comment]
Does the server have Spigot? Spigot breaks this mod.

**Comment by Francy-chan** [comment]
Yes, it was running on Spigot.

**Comment by MoriyaShiine** [comment]
Yeah, unfortunately there's nothing I can do about this. Sorry :(
