### ISSUE TITLE
Crash on launch with the SIHYWTCAMD mod

### ISSUE THREAD

**Issue by MScott7** [MoriyaShiine/on-soul-fire#8]
### Mod version

1.18-3

### A description of the issue

Minecraft crashes on launch when On Soul Fire is installed alongside the mod SIHYWTCAMD (So I Heard You Were Talking Crap About Minecraft's Difficulty). Sorry if this should be filed with them instead.

Fabric loader 0.14.9
Fabric API version 0.58.0+1.18.2
On Soul Fire version 1.18-3
SIHYWTCAMD version 1.7+1.18.2

https://www.curseforge.com/minecraft/mc-mods/sihywtcamd

### Log or crash report

https://gist.github.com/MScott7/d373623b60fd03ca42fe1231e802eff1

**Comment by MoriyaShiine** [comment]
Looking at their code, this seems to be fixed by now
